# Generated by Django 3.2.9 on 2021-11-13 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique_for_date='timestamp')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('price', models.IntegerField(max_length=10)),
                ('image', models.CharField(max_length=250)),
                ('favorite', models.BooleanField(null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='timestamp')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_app.cart')),
            ],
        ),
    ]
